version: 2
jobs:
  build:
    environment:
      DJANGO_IMAGE_NAME: codeleak/codeleak-django-backend
      NEXT_IMAGE_NAME: codeleak/codeleak-nextjs
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
      - run:
          name: Build Django Docker image
          command: docker build -t $DJANGO_IMAGE_NAME:latest -t $DJANGO_IMAGE_NAME:$CIRCLE_SHA1 ./django-backend
      - run:
          name: Build NextJS image
          command: docker build -t $NEXT_IMAGE_NAME:latest -t $NEXT_IMAGE_NAME:$CIRCLE_SHA1 .

  deploy:
    environment:
      DJANGO_IMAGE_NAME: codeleak/codeleak-django-backend
      NEXT_IMAGE_NAME: codeleak/codeleak-nextjs
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "lamerajlame4321"
            docker push $DJANGO_IMAGE_NAME:latest
            docker push $DJANGO_IMAGE_NAME:$CIRCLE_SHA1
            docker push $NEXT_IMAGE_NAME:latest
            docker push $NEXT_IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          # filters:
          #   branches:
          #     only: master
      - deploy:
          # filters:
          #   branches:
          #     only: master