# Generated by Django 2.1.7 on 2019-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_this_week',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
