# Generated by Django 2.2 on 2019-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190419_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercommentvote',
            name='vote_value',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='vote_value',
        ),
        migrations.RemoveField(
            model_name='questioncommentvote',
            name='vote_value',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='vote_value',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='answercommentvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answervote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questioncommentvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='used_times',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
