# Generated by Django 2.2 on 2019-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answercommentreport_answerreport_questioncommentreport_questionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='repository_url',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
