# Generated by Django 2.1.7 on 2019-08-11 01:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190603_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dependencies',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='dependencies',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
