# Generated by Django 2.1.7 on 2019-08-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190811_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dependencies',
        ),
    ]
