# Generated by Django 2.1.7 on 2019-08-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190811_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='stackblitz_template',
            field=models.CharField(default='create-react-app', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='stackblitz_template',
            field=models.CharField(default='create-react-app', max_length=100),
            preserve_default=False,
        ),
    ]
