version: '3'

services:
  web:
    build: .
    command: python /code/codeleak_backend/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/dev.env
    # networks: 
    #   - postgres_django
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  db:
    image: postgres
    restart: always
    networks:
      - postgres_django
    environment:
      POSTGRES_USER: codeleak_user
      POSTGRES_DB: codeleak
      POSTGRES_PASSWORD: abcdefghijklmnopqrstuvwxyz 
    ports:
      - '5432:5432'
networks:
  postgres_django:
    external: true
  
